### ISSUE TITLE
[TRACKING] Move all packages into subpackages

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#2404]
- [x] Move core (#2367, #2394, #2393, #2392)
- [x] Move `bigtable` (#2410)
- [x] Update `Makefile.bigtable_v2` (or hopefully just depend on an autogenerated package, #2128) (#2452)
- [x] Put `happybase` repo on top of `bigtable` implementation (https://github.com/GoogleCloudPlatform/google-cloud-python-happybase/pull/9, https://github.com/GoogleCloudPlatform/google-cloud-python-happybase/pull/10, https://github.com/GoogleCloudPlatform/google-cloud-python-happybase/pull/11, https://github.com/GoogleCloudPlatform/google-cloud-python-happybase/pull/12, https://github.com/GoogleCloudPlatform/google-cloud-python-happybase/pull/13, https://github.com/GoogleCloudPlatform/google-cloud-python-happybase/pull/14, https://github.com/GoogleCloudPlatform/google-cloud-python-happybase/pull/15)
- [x] Move `bigquery` (#2418)
- [x] Move `storage` (#2416)
- [x] Move `datastore` (#2417)
- [x] Update `Makefile.datastore` (or hopefully just depend on an autogenerated package, #2128) (#2452)
- [x] Move `pubsub` (#2419)
- [x] Move `logging` (#2420)
- [x] Fix RTD breakage (#2405, #2444, #2445, #2453, #2455)
- [x] Move `language` (#2429)
- [x] Move `vision` (#2433)
- [x] Move `speech` (#2431, #2438)
- [x] Move `monitoring` (#2430)
- [x] Move `resource_manager` (#2435)
- [x] Move `translate` (#2432)
- [x] Move `dns` (#2428)
- [x] Move `error_reporting` (#2436)
- [x] Fix-up `::` lines in `README` files (https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2428#discussion_r80564909, #2581)
- [x] Fix install from source instructions (#2437, #2447)
- [ ] Make testing fast again (after compromises during rename) (#2484, #2475, #2473, #2481)
- [ ] Figure out how to shadow `google-cloud-natural-language` (https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2429#discussion_r80566704, https://gist.github.com/dhermes/a4e097f2f80fd490b256fc3aa2b4a46b)
- [x] Determine proper upper / lower bounds on `grpcio` and `google-cloud-core` (https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2417#discussion_r80393856)
- [x] Edit global / umbrella `README` to refer to all subpackages (#2442)
- [ ] Make script for running coverage report
- [ ] Make script for running `tox` envs in Travis (Along the lines of #2277)
- [ ] DRY in `setup.py` (#2395)
- [ ] DRY for `.coveragerc`, `MANIFEST.in` and `setup.cfg`
- [x] Figure out the user agent (#2391)
- [x] Script using `twine` to upload packages on tags (relevant: https://github.com/GoogleCloudPlatform/gcloud-common/issues/138#issuecomment-220830613, #2462) (#2837) 
- [ ] Make a package for all the shared code needed in system tests / or just decide to leave the system tests alone where they are (#2458)

**Comment by dhermes** [comment]
@omaray Via #2441 I just made releases of "all" of our packages:

https://pypi.python.org/pypi/google-cloud-core/0.20.0
https://pypi.python.org/pypi/google-cloud-bigquery/0.20.0
https://pypi.python.org/pypi/google-cloud-bigtable/0.20.0
https://pypi.python.org/pypi/google-cloud-pubsub/0.20.0
https://pypi.python.org/pypi/google-cloud-storage/0.20.0
https://pypi.python.org/pypi/google-cloud-datastore/0.20.0
https://pypi.python.org/pypi/google-cloud-logging/0.20.0
https://pypi.python.org/pypi/google-cloud-monitoring/0.20.0
https://pypi.python.org/pypi/google-cloud-language/0.20.0
https://pypi.python.org/pypi/google-cloud-natural-language/0.20.0
https://pypi.python.org/pypi/google-cloud-dns/0.20.0
https://pypi.python.org/pypi/google-cloud-error-reporting/0.20.0
https://pypi.python.org/pypi/google-cloud-resource-manager/0.20.0
https://pypi.python.org/pypi/google-cloud-translate/0.20.0
https://pypi.python.org/pypi/google-cloud-vision/0.20.0
https://pypi.python.org/pypi/google-cloud/0.20.0

So @jonparrott you can start updating samples if you like.

**Comment by omaray** [comment]
Sweet!
