### ISSUE TITLE
Tracking Speech API development.

### ISSUE THREAD

**Issue by daspecster** [GoogleCloudPlatform/google-cloud-python#2522]
These are the items required to reach feature completion.
- [x] Use Transcript object for sync and async requests. (#2613)
- [x] GAPIC Sync Recognize (#2615)
- [x] GAPIC Async Recognize(#2638, #2663)
- [x] Streaming recognize (#2523, #2640,#2644, #2680)
- [x] Add stability information to streaming interim_results (https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2702)
- [x] Add `sync_recognize` system tests (#2547)
- [x] Add `async_recognize` system tests (#2648)

## Cleanup
- [x] Update `SpeechContext` in tests. See: https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2700. (#2717)
- [x] Add PyPI [badges](https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2685) (#2716)
- [x] Rename `Transcript` to `Alternative`. (#2666)
- [x] Test cleanup (#2676)
- [x] Run skipped tests(https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2648#discussion_r85783495)
- [x] Move sample to Client property. See: #2516
- [x] Remove warning about `google-cloud-speech` not yet released. See: #2620 (#2732)

### Future Updates:
- Clearer way to send stream to `Sample.content` (https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2708)
-  Move result access to Operation handler https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2638#discussion_r85596232
- Add snippet tests (optional for release)

**Comment by daspecster** [comment]
@dhermes I commented on your gist from today but I'll copy it here as well...
Ref: https://gist.github.com/dhermes/09c964d6d27003ae817b650424fda7c3

--------

Thank you for this!

I have another question.
As you saw in your output here, the final result has a `response` attribute.

In the [sample](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/d7dc5780cd975ed5927e68bd5dd5a4a69ce5efb5/speech/grpc/transcribe_async.py#L94-L95) the way that you unpack the response is via
```python
response = cloud_speech_pb2.AsyncRecognizeResponse()
operation.response.Unpack(response)
```

But that has to be done after the Operation is completed.
How would we handle that in `google-cloud-python`?

The point of async is not to block right? If our lib has to wait until the operation is complete before the data can be unpacked then it would block right?

One thought I had was to add a helper of some kind that unpacks the data for us.

```python
import time
from google.cloud import speech
from google.cloud.speech.encoding import Encoding

client = speech.Client()
sample = client.sample(source_uri='gs://ferrous-arena-my-test-bucket/sample.raw', encoding=Encoding.LINEAR16, sample_rate=16000)

operation = client.async_recognize(sample, max_alternatives=2)

retry_count = 10
while retry_count > 0 and not operation.complete:
    retry_count -= 1
    time.sleep(1)

    operation.poll()  # API call

for result in speech.unpack_async(operation):  # The helper `unpack_async`.
        print('Result:')
        for alternative in result.alternatives:
            print(u'  ({}): {}'.format(
                alternative.confidence, alternative.transcript))
```

But otherwise I'm not sure how to get the data without blocking unless we do some kind of weird pubsub design.

**Comment by daspecster** [comment]
Scratch that...we could just parse it in `Operation.poll()` right? I think I would have to either override `google.cloud.core.operation.Operation.poll` or I could add some kind of polling proxy method.

**Comment by dhermes** [comment]
@daspecster It's not up to use to get the data, just give the user the `Operation` and let them decide how to poll.

**Comment by fehrenbacher** [comment]
Is this available yet? I've installed `google-cloud` 0.20.0, but can't find the `google.cloud.speech.client.Client` class. I've also found [this page](https://pypi.python.org/pypi/google-cloud-speech) for a separate `google-cloud-speech` library, but pip can't find any actual releases there. The [documentation](https://googlecloudplatform.github.io/google-cloud-python/stable/speech-usage.html) sure makes it sound like this is available to use now...

**Comment by gw00207** [comment]
@fehrenbacher yes, that documentation is confusing. hopefully a message is added soon to explain: #2620

**Comment by daspecster** [comment]
@fehrenbacher it's not released yet, however if you install from source you can play with the API.

As you can see in the first link, it's at the "Planning" stage. That package is a place holder.

The documentation message hasn't gone up because there hasn't been a release yet. We're working on a better release strategy as well.

**Comment by fehrenbacher** [comment]
K thanks for clearing that up!

**Comment by daspecster** [comment]
@fehrenbacher it's my mistake with having the docs out there. I think I have a better process for next time. If you decide to install from source and play with it, please let me know if you run into any issues!

I have a handful of things I'm working to resolve this week and then I'm hoping we will be able to release it.

See: https://github.com/GoogleCloudPlatform/google-cloud-python/issues?q=is%3Aissue+is%3Aopen+label%3Aspeech

**Comment by gw00207** [comment]
@daspecster nice :-) looking forward to it!

**Comment by daspecster** [comment]
Closing this since everything is complete and I opened #2842 to track the last few little changes.
