### ISSUE TITLE
Tracking Vision Development.

### ISSUE THREAD

**Issue by daspecster** [GoogleCloudPlatform/google-cloud-python#2753]
There are some things missing in vision that should be added to complete the service.

- [x] Add support for `image = client.image(filename='./my.jpg')`. (#2778, #2792)
- [x] Make public method for multiple annotation detection(#2770).
- [x] Move emotion attributes directly to face. `face.joy` instead of `face.emotions.joy`. (#2782)
- [x] Add system tests #2526. (#2788, #2827, #2830, #2834, #2835, #2836, #2839)
- [x] Add GAPIC support. (#2914, #2918, #2922, #2937, #2938)
- [x] Add batch processing, annotation multiple images with one request.(#2897, #2967, #2978)
- [ ] Rename Face.Landmark to something like Face.FacialFeature(https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2833#discussion_r91315815).
- [ ] Move snippets to `docs/vision_snippets.py`.
- [ ] Add more examples and update documentation(#2754).
- [ ] Refactor unit tests.

**Comment by lukesneeringer** [comment]
Long since launched.
