### ISSUE TITLE
Test all links and code examples in docs for GA/Beta.

### ISSUE THREAD

**Issue by daspecster** [GoogleCloudPlatform/google-cloud-python#3172]
Test all doc links and examples for...

- [x] BigQuery ([results](https://gist.github.com/daspecster/2c928e30b287e7c2ea63dabbafdaec61))
  - [x] Links/references (#3196)
  - [x] Examples/Snippets
- [x] Datastore 1 anchor reference error, ([results](https://gist.github.com/daspecster/1385b1675f4a923998d7c698fe99c328))
  - [x] Links/references (#3186)
  - [x] Examples/Snippets
- [x] Storage 
  - [x] Links/references (#3192) ([results](https://gist.github.com/daspecster/04c384e26464210a272fbc0b3dd8a6f9))
  - [x] Examples/Snippets (generate_upload_policy snippet appears to be broken) ([results](https://gist.github.com/daspecster/8735dcb1d8139e99eaf4bb7fc2fc28f9)) (PR: #3221)
- [x] Logging ([results](https://gist.github.com/daspecster/78b39c836f38ff93abb6c6faae227062))
  - [x] Links/references (#3187)
  - [x] Examples/Snippets (Issue(s): #3218) (PR: #3219), ([results](https://gist.github.com/daspecster/616fadeadfeb904c9892a33dc9f7bbf3))
- [x] Natural Language
  - [x] Links/references (#3197)
  - [x] Examples/Snippets ([results](https://gist.github.com/daspecster/ed566b5a63f3a7e50c879e05d4c30f09)) (PR: #3220)
- [x] Speech
  - [x] Links/references (#3198)
  - [x] Examples/Snippets (PR: #3206) ([results](https://gist.github.com/daspecster/718d01c7896ee576743292549cfb6927))
- [x] Translation
  - [x] Links/references (#3199)
  - [x] Examples/Snippets ([results](https://gist.github.com/daspecster/9dafcf98ea0e34de7f7203a224e3d0d6))
- [x] Vision
  - [x] Links/references (#3202)
  - [x] Examples/Snippets ([results](https://gist.github.com/daspecster/ef07af75de71f3694282f7b020962f00)) PR: #3227

/cc @lukesneeringer @omaray

**Comment by dhermes** [comment]
This is in some sense the grandchild of #212. I vote for the approach used in #2738.

**Comment by daspecster** [comment]
Moving discussion from https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3206#issuecomment-289135807 to this thread.

@lukesneeringer so here's the current status of snippets for GA.

- Datastore snippet tests work/pass and are the most current architecture.
- BigQuery snippet tests work/pass but they are the old architecture and need to be updated.
- Storage snippet tests do not work and are the old architecture.
- Logging snippet tests do not exists.

The Right Thing™ to do is probably update the BigQuery and Storage snippets to the same methodology that Datastore is using. I think that can be done in reasonable time. Logging however, is pretty huge and may take a fair bit of work.

I thought this was already a known, and that's why manual testing was the preferred route for now.

**Comment by dhermes** [comment]
@daspecster FYI: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/1bcff68a53435301e1f309d634420703ec8c2464/docs/logging_snippets.py

**Comment by dhermes** [comment]
> that's why manual testing was the preferred route for now.

There is an inflection point where doing things "by hand" starts to become longer than doing it the right way

**Comment by daspecster** [comment]
@dhermes logging_snippets.py looks fairly outdated.

```bash
╰─$ python docs/logging_snippets.py
instantiate_client       : Instantiate client.
  ERROR: ValueError('This library only supports credentials from google-auth-library-python. See https://google-cloud-python.readthedocs.io/en/latest/google-cloud-auth.html for help on authentication with this library.',)
client_list_entries      : List entries via client.
  ERROR: TypeError('Can not find message descriptor by type_url: type.googleapis.com/google.cloud.audit.AuditLog.',)
logger_usage             : Logger usage.
metric_crud              : Metric CRUD.
sink_storage             : Sink log entries to storage.
sink_bigquery            : Sink log entries to bigquery.
sink_pubsub              : Sink log entries to pubsub.
logging_handler          : None
  ERROR: TypeError('logging_handler() takes exactly 1 argument (2 given)',)
setup_logging            : None
  ERROR: TypeError('setup_logging() takes exactly 1 argument (2 given)',)
```

**Comment by dhermes** [comment]
I am unaware of how up to date it is, just posted as a response to "Logging snippet tests do not exists."

**Comment by daspecster** [comment]
@dhermes yeah thanks! I updated the status in the list.

**Comment by daspecster** [comment]
@dhermes the Storage [snippet for generate_upload_policy](https://googlecloudplatform.github.io/google-cloud-python/stable/storage-buckets.html#google.cloud.storage.bucket.Bucket.generate_upload_policy) seems to be broken. I looked at [the docs](https://cloud.google.com/storage/docs/xml-api/post-object#policydocument) but I don't see where the breakdown is.

Here's the output when trying to upload with the generated HTML form.

```xml
<Error>
<Code>InvalidArgument</Code>
<Message>Invalid argument.</Message>
<Details>Cannot create buckets using a POST.</Details>
</Error>
```

Any ideas?

**Comment by dhermes** [comment]
@jonparrott Wrote the snippet.

**Comment by jonparrott** [comment]
It's probably fine, it's just that the bucket has to exist.

**Comment by daspecster** [comment]
@jonparrott in my test, I was/am using a bucket that exists.

**Comment by jonparrott** [comment]
Weird. That error message indicates otherwise!

**Comment by daspecster** [comment]
@jonparrott haha I know! 😕

**Comment by jonparrott** [comment]
Can you try manually verifying it?

**Comment by daspecster** [comment]
@jonparrott yeah that's how I'm getting the error. I'm not just running the snippets. The storage snippets need some updating to work.

```python
bucket = client.bucket('my-bucket24356uytrew')
conditions = [
    ['starts-with', '$key', ''],
    {'acl': 'public-read'}]

policy = bucket.generate_upload_policy(conditions)

# Generate an upload form using the form fields.
policy_fields = ''.join(
    '<input type="hidden" name="{key}" value="{value}">'.format(
        key=key, value=value)
    for key, value in policy.items()
)

upload_form = (
    '<form action="http://{bucket_name}.storage.googleapis.com"'
    '   method="post" enctype="multipart/form-data">'
    '<input type="text" name="key" value="">'
    '<input type="hidden" name="bucket" value="{bucket_name}">'
    '<input type="hidden" name="acl" value="public-read">'
    '<input name="file" type="file">'
    '<input type="submit" value="Upload">'
    '{policy_fields}'
    '<form>').format(bucket_name=bucket.name, policy_fields=policy_fields)

print(upload_form)
```

**Comment by jonparrott** [comment]
Hmm. I'm at a a bit of a loss.

**Comment by daspecster** [comment]
I was able to get the logging snippets running somewhat.

```bash
instantiate_client       : Instantiate client.
  ERROR: ValueError('This library only supports credentials from google-auth-library-python. See https://google-cloud-python.readthedocs.io/en/latest/google-cloud-auth.html for help on authentication with this library.',)
client_list_entries      : List entries via client.
  ERROR: TypeError('Can not find message descriptor by type_url: type.googleapis.com/google.cloud.audit.AuditLog.',)
logger_usage             : Logger usage.
metric_crud              : Metric CRUD.
sink_storage             : Sink log entries to storage.
sink_bigquery            : Sink log entries to bigquery.
sink_pubsub              : Sink log entries to pubsub.
logging_handler          : None
setup_logging            : None
```

**Comment by jonparrott** [comment]
@daspecster can you file a separate bug about the storage policy document stuff and assign it to me? Thanks!

**Comment by daspecster** [comment]
@jonparrott sure thing!

https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3222

**Comment by daspecster** [comment]
Ok, just a few PR's to merge and I think we're pretty much there.

- #3219 
- #3220 
- #3206 
- #3227

**Comment by daspecster** [comment]
Ok all the PRs are merged.

I'm not saying the docs are perfect but they should be a lot closer.

I'm going to close this issue since all the outlined tasks are completed.

**Comment by lukesneeringer** [comment]
:tada:, thanks.
