### ISSUE TITLE
Make releases for all packages with user-visible feature / bugfixes

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#3533]
Release needed:

- [x] core-0.25.0 (PR #3526)
- [x] datastore-1.1.0 (PR #3527)
- [x] logging-1.1.0 (PR #3528)
- [x] storage-1.2.0 ~~(exclude "requester pays") (PR #3529)~~ (PR #3540)
- [x] bigquery-0.25.0 (PR #3530)
- [x] pubsub-0.26.0 (PR #3532)
- [x] bigtable-0.25.0 (PR #3534)
- [x] language-0.25.0 (PR #3535)
- [x] vision-0.25.0 (PR #3537)

No release needed, exception for "release the world" to pick up new `google-cloud-core`:

- [x] dns-0.25.0 (PR #3541)
- [x] error_reporting-0.25.0 (PR #3542)
- [x] monitoring-0.25.0 (PR #3543)
- [x] resource_manager-0.25.0 (PR #3544)
- [x] runtimeconfig-0.25.0 (PR #3545)
- [x] spanner-0.25.0 (PR #3536)
- [x] speech-0.26.0 (PR #3546)
- [x] translate-0.25.0 (PR #3547)

No release needed at all:

- videointelligence does not depend on `google-cloud-core`.

Finally:

- [x] Umbrella release (PR #3549)

**Comment by tseaver** [comment]
See:

https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/0.26.0
