### ISSUE TITLE
Bigquery Beta 2 Tracking

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#3746]
Target all work for the project to a new `bigquery-b2` branch.

## P0 Tasks

- [x] Rename job classes: `LoadTableFromStorageJob` -> `LoadJob`, `ExtractTableToStorageJob` -> `ExtractJob` (PR #3797)
- [x] Rename ACL entry: `dataset.AccessGrant` -> `dataset.AccessEntry`, and likewise `Dataset.access_grants` -> `Dataset.access_entries`. (PR #3798)
- [ ] `Client.get_job`:  construct concrete job instance from job ID via `jobs.get` API (PR #3804)
- [ ] `QueryJob`:  add `result` method returning future-ish object which polls both the job and the result until done;  then returns rows via `Table.fetch_data` on the destination table.
- [ ] Implement high-level `Client.query` method: waits for completion, returns rows
- [ ] Generate job IDs only on Client-side if not supplied by the user.
- [ ] Add support for retries to streaming insert
- [ ] Add support for external tables (issue #2372)
- [ ] Add etag support to `Dataset.patch` / `Dataset.update`
- [ ] Add etag support to `Table.patch` / `Table.update`
- [ ] Add support for `Table.streamingBuffer`
- [ ] Add CRUD for Dataset labels (issue #2931)
- [ ] Add CRUD for Table labels (issue #2931)

## P1 Tasks

- [ ] Add support for client-side job ID generation with user-supplied prefix
- [ ] Add support for Dataset ACLs
- [x] Expose returned query plan (`Job.statistics.query.queryPlan`) (PR #3799)
- [ ] Add support for creating table on insert (`TableData.insertAll` to non-existent table)

## Other tasks

- [ ] Migrate new job statistics work (from PR #3721) (PR #3799, #3800, #3801, #3802, #3803)

**Comment by lukesneeringer** [comment]
@tseaver Thanks for putting this together!

**Comment by lukesneeringer** [comment]
@danoscarmike Not entirely sure how to assign "priority" for a ticket like this. It does not fit cleanly.

**Comment by danoscarmike** [comment]
As this is dev work tracked internally I don't think it needs a priority here. Clearly it is useful butt I would say 'enhancement' suffices for triage.

**Comment by danoscarmike** [comment]
but, even

**Comment by lukesneeringer** [comment]
> As this is dev work tracked internally I don't think it needs a priority here. Clearly it is useful butt I would say 'enhancement' suffices for triage.

Your script will disagree.

**Comment by tseaver** [comment]
@tswast, @alixhami, and @jba are doing the work per a different design spec.
