### ISSUE TITLE
Additional spanner integration tests.

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#4364]
For spanner GA.  Investigate whether these are already tested, and add tests as appropriate.  Link either PR # or line reference of existing test.

- [x] Read single key
https://github.com/GoogleCloudPlatform/google-cloud-python/blob/6c602823e7101b40dfe5bfc614da633beb8accfb/spanner/tests/system/test_system.py#L840-L850
- [x] Read single key w/ index (#4403)
- [x] Range read w/ single key (#4573)
- [x] Range read w/ partial key (#4631)
- [x] Range read over index w/ open/open range (#4411)
- [x] Range read over index w/ open/closed range (#4411)
- [x] Range read over index w/ closed/open range (#4411)
- [x] Range read over index w/ closed/closed range (#4411)
- [x] Bind string to null (#4371)
- [x] Bind timestamp (#4371)
- [x] Bind date https://github.com/GoogleCloudPlatform/google-cloud-python/blob/f69d704841bd30c08af4a522397b3fe95107bdfd/spanner/tests/system/test_system.py#L673-L679
- [x] Bind string array (#4371)
- [x] Bind empty string array (#4371)
- [x] Query returning array of `-Inf`, `+Inf`, `Nan` (#4371)
- [x] Write / read back null string (#4372)
- [x] Write / read back empty array of string (#4372)
- [x] Write / read back null array of string (#4372)
- [x] Write / read back array of string with mixed null / non-null values (#4372)
- [x] Writing incorrect type of value should fail (#4569 )

/cc @lukesneeringer

**Comment by tseaver** [comment]
@chemelnucfin Thanks for the updates!  As we each begin adding one or more related tests, let's adopt the covention of marking the checkbox items with our handles (to avoid duplicating effort).

**Comment by tseaver** [comment]
@chemelnucfin I had to uncheck some of the boxes :( -- the test description was missing "*over index*".

**Comment by chemelnucfin** [comment]
What is range read with partial key?

**Comment by chemelnucfin** [comment]
Never mind, got it.

**Comment by chemelnucfin** [comment]
Closed via PRs from above
