### ISSUE TITLE
Drop usage of gax in favor of api_core

### ISSUE THREAD

**Issue by jonparrott** [GoogleCloudPlatform/google-cloud-python#4692]
We are trying to deprecate gax in favor of api_core, and to do so, we must remove all usage of gax here.

The following libraries still have references/use gax:

- [x] bigtable: only uses gax.metrics, should be trivial to fix. https://github.com/GoogleCloudPlatform/google-cloud-python/pull/4873
- [x] datastore: has generated code that uses gax, and hand-written adapter over gapic client. Needs to be regenerated and the adapter code likely needs to be updated (one quick glance, most of it can be removed). #4877
- [x] error reporting: depends on the now-legacy separate gapic package. generated code needs to be co-located. Additionally has a small adapter like datastore which can mostly be removed. #4743
- [ ] firestore:  has generated code that uses gax. Needs to be regenerated. Has two small helpers for remapping gax errors (can be deleted) and adding metadata (will need to just be moved to the callsite). @chemelnucfin made a stab at this in the closed-without-merging PR #4880.
- [x] logging: depends on the now-legacy separate gapic package. generated code needs to be co-located. Additionally has an adapter like datastore which can mostly be removed. #4759
- [x] spanner: has generated code that uses gax. Needs to be regenerated. Has one helper that adds metadata which can be moved to the callsite. #4695
- [x] speech: has generated code that uses gax, and hand-written adapter over gapic client. Needs to be regenerated and the adapter code likely needs to be updated (one quick glance, most of it can be removed). This also has an error where `speech` is not a strict alias of `speech_v1`. #4788
- [x] trace: depends on the now-legacy separate gapic package. generated code needs to be co-located. Additionally has an adapter like datastore which can mostly be removed. https://github.com/GoogleCloudPlatform/google-cloud-python/pull/4799

**Comment by tseaver** [comment]
I'm pulling "priority: p2+" of issues labeled "type: cleanup" , because that label is supposed to be used for non-SLO-impacting stuff (normally things we open ourselves to handle at will later).

For this one, I don't know whether we should remove "type: cleanup" or "priority: p1", but one of them should go. :)

**Comment by jonparrott** [comment]
How about we swap process for cleanup? :)

**Comment by tseaver** [comment]
Sure. :)

**Comment by chemelnucfin** [comment]
@lukesneeringer @jonparrott if one of you can kinda walk me through a bit of the process I can try to take some of these out.

I don't understand the autogenerator in tookit enough I think to do this, but I would be interested in understanding it.

**Comment by jonparrott** [comment]
I just send an email, but I'm going to handle the first couple myself. I'm working on error_reporting now.
