### ISSUE TITLE
Spanner v1.0.0 release

### ISSUE THREAD

**Issue by jonparrott** [GoogleCloudPlatform/google-cloud-python#4710]
This bug tracks the criteria for releasing v1.0.0 of Spanner.

The following items need to be completed:

- [x] Update gapic code. #4695
- [x] Remove dependency on deprecated gax library. #4695
- [x] Release new `api_core`, since it contains changes that Spanner needs. #4730
- [x] Release a release candidate. #4732
- [x] Have a Storage DPE review the API surface & documentation. (@jsimonweb)
- [x] Have a Python DPE review the API surface for overall API consistency. (@jonparrott)
- [x] Have Spanner POC review the API surface & documentation. (@vkedia)
- [x] Wait one week and resolve any user issues.
- [x] Release v1.0.0. ✨

**Comment by jonparrott** [comment]
@jsimonweb @vkedia can you please review v0.30.0 of the client library and it's [documentation](https://google-cloud-python.readthedocs.io/en/latest/spanner/usage.html)?

**Comment by lukesneeringer** [comment]
@jonparrott We are requiring `api_core` to go to 1.0 in order for Spanner to do so, yes? (I assume it is in a similar "wait a week" state at the moment.)

**Comment by vkedia** [comment]
Some corrections need to be done on the documentation:

Code snippet on [this](https://google-cloud-python.readthedocs.io/en/latest/spanner/batch-usage.html) page talks about `session.batch()` instead of `client.batch()`.

On [snapshots](https://google-cloud-python.readthedocs.io/en/latest/spanner/snapshot-usage.html) page we talk about user having to resume the stream but now we do it automatically so it should be removed.

On [snapshots](https://google-cloud-python.readthedocs.io/en/latest/spanner/snapshot-usage.html) page (and probably elsewhere) we show iterator over rows as `for row in result.rows`. But this is incorrect since we now removed the `rows` property.

Read write transactions [https://google-cloud-python.readthedocs.io/en/latest/spanner/transaction-usage.html] page talks about manually managing the transaction. Instead it should talk about `run_in_transaction` method.

**Comment by vkedia** [comment]
Why are the `to_pb` methods part of public api in [KeySet](https://google-cloud-python.readthedocs.io/en/latest/spanner/keyset-api.html#google.cloud.spanner_v1.keyset.KeyRange.to_pb) ?

**Comment by jonparrott** [comment]
> Why are the to_pb methods part of public api in KeySet ?

@tseaver @dhermes do either of you know? I'm happy to make them private.

**Comment by chemelnucfin** [comment]
@vkedia we use context managers for managing transactions, and allow users to manually managing transaction if they wish.  Should we take out the run_in_transaction method?

**Comment by jonparrott** [comment]
@lukesneeringer 

> We are requiring api_core to go to 1.0 in order for Spanner to do so, yes? (I assume it is in a similar "wait a week" state at the moment.)

No. I'm waiting to v1.0.0 api_core once #4692 is closed so we can v1.0.0 api_core and kill gax at the same time.

**Comment by vkedia** [comment]
@chemelnucfin `run_in_transaction` is the primary method which we expect people to use. Most users should not need to manage transactions manually. I want to make sure that this comes through in the docs clearly.

**Comment by jonparrott** [comment]
I've reviewed the api surface and found no inconsistencies with our overall python libraries nor anything that causes concern for version thrashing post-GA. This can launch.

**Comment by jonparrott** [comment]
@tseaver do you mind cutting the release PR?

**Comment by chemelnucfin** [comment]
@jonparrott what about making the to_pb methods private?

**Comment by jonparrott** [comment]
Should we?

**Comment by chemelnucfin** [comment]
My thoughts on that are that it breaks current compatibility, but it is overall a better decision.

Obviously it's all usable anyway, so I guess the risk here is how big is the risk to break current compatibility.  But it's probably better done now than later.

**Comment by jonparrott** [comment]
cool, let's do it then. Do you mind sending the PR to do that?

**Comment by chemelnucfin** [comment]
See #4740

**Comment by chemelnucfin** [comment]
@jonparrott Since we are breaking changes, should session also be changed to non-public then?  
[Session](https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3740#issuecomment-345112082)
I was hesitant to do it because it was a breaking change and that didn't go well before.

**Comment by jonparrott** [comment]
I don't think we should make the session class private.

**Comment by jonparrott** [comment]
@tseaver wdyt?

**Comment by chemelnucfin** [comment]
@jonparrott [Session](https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3740#issuecomment-348564023).
Sorry, wrong comment.

**Comment by tseaver** [comment]
Totally don't wanna make the session class private:  more advanced users may definitely need to use it.

**Comment by jonparrott** [comment]
Cool, let's get a release PR drafted. @chemelnucfin do you want to take that on? (if not, I'll do it tomorrow morning).
